"""Added rooms

Revision ID: 305237ee15b0
Revises: 
Create Date: 2021-02-10 15:57:54.396384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '305237ee15b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', sa.String(length=4), nullable=False),
    sa.Column('last_activation', sa.Integer(), nullable=True),
    sa.Column('placement', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room')
    # ### end Alembic commands ###
